name: Test

on:
  push:
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "src/**"
      - ".github/**"
    branches:
      - next

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          echo $HOME/.cargo/bin >> $GITHUB_PATH
      - name: Test
        run: cargo test
